[package]
name = "i4"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
uapi = "0.2.4"
thiserror = "1.0.30"
ahash = "0.7.6"
log = "0.4.14"
env_logger = "0.9.0"
futures = "0.3.19"
num-traits = "0.2.14"
num-derive = "0.3.3"
bitflags = "1.3.2"
xcb-dl = "0.2.0"
xcb-dl-util = { version = "0.2.0", features = ["xcb_shm", "xcb_xinput", "xcb_xkb"]}
libloading = "0.7.2"
bstr = "0.2.17"
isnt = "0.1.0"

[build-dependencies]
repc = "0.1.1"
anyhow = "1.0.52"
