[package]
name = "i4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
uapi = "0.2.4"
thiserror = "1.0.30"
anyhow = "1.0.52"
ahash = "0.7.6"
log = "0.4.14"
env_logger = "0.9.0"
futures = "0.3.19"
waker-fn = "1.1.0"
