[package]
name = "i4"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[workspace]
members = ["i4config", "default-config"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
uapi = "0.2.7"
thiserror = "1.0.30"
ahash = "0.7.6"
log = "0.4.14"
env_logger = "0.9.0"
futures = "0.3.19"
num-traits = "0.2.14"
num-derive = "0.3.3"
bitflags = "1.3.2"
xcb-dl = "0.2.0"
xcb-dl-util = { version = "0.2.0", features = ["xcb_shm", "xcb_xinput", "xcb_xkb", "xcb_dri3", "xcb_present", "xcb_render"]}
libloading = "0.7.2"
bstr = "0.2.17"
isnt = "0.1.0"
once_cell = "1.9.0"
rand = "0.8.4"
renderdoc = "0.10.1"
smallvec = { version = "1.8.0", features = ["const_generics", "const_new", "union"] }
backtrace = "0.3.64"
byteorder = "1.4.3"
chrono = "0.4.19"
bincode = "2.0.0-beta.3"
pangocairo = "0.15.1"
cairo-rs = { version = "0.15.1", features = ["png"] }
pango = { version = "0.15.2", features = ["v1_44"] }
i4config = { path = "i4config" }
default-config = { path = "default-config" }
x11rb = { version = "0.9.0", features = ["composite"] }

[build-dependencies]
repc = "0.1.1"
anyhow = "1.0.52"
bstr = "0.2.17"

[profile.dev.build-override]
opt-level = 3

[features]
rc_tracking = []
