[package]
name = "jay"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[workspace]
members = ["jay-config", "default-config"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
uapi = "0.2.7"
thiserror = "1.0.30"
ahash = "0.7.6"
log = "0.4.14"
env_logger = "0.9.0"
futures-util = "0.3.19"
num-traits = "0.2.14"
num-derive = "0.3.3"
bitflags = "1.3.2"
libloading = "0.7.2"
bstr = "0.2.17"
isnt = "0.1.0"
once_cell = "1.9.0"
rand = "0.8.4"
smallvec = { version = "1.8.0", features = ["const_generics", "const_new", "union"] }
backtrace = { version = "0.3.64", optional = true }
byteorder = "1.4.3"
chrono = "0.4.19"
bincode = "2.0.0-beta.3"
jay-config = { path = "jay-config" }
default-config = { path = "default-config" }
pin-project = "1.0.10"

[build-dependencies]
repc = "0.1.1"
anyhow = "1.0.52"
bstr = "0.2.17"

#[profile.dev.build-override]
#opt-level = 3

[features]
rc_tracking = ["backtrace"]
